// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlTHXOO54-GFLAorpTTeR_Ff0bdxVoWAc',
    appId: '1:369538743828:web:8ec180dd319780c6e97101',
    messagingSenderId: '369538743828',
    projectId: 'todoapp-583d0',
    authDomain: 'todoapp-583d0.firebaseapp.com',
    storageBucket: 'todoapp-583d0.appspot.com',
    measurementId: 'G-HMWMZSEY9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIwafg72T5xH6DEhwB9Jb2GTDWe5eISoM',
    appId: '1:369538743828:android:b1c325ff9a8ab1a7e97101',
    messagingSenderId: '369538743828',
    projectId: 'todoapp-583d0',
    storageBucket: 'todoapp-583d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWBEvoPmuUCmqeTOCP66LWEQAKvufujus',
    appId: '1:369538743828:ios:1375c859fa41e346e97101',
    messagingSenderId: '369538743828',
    projectId: 'todoapp-583d0',
    storageBucket: 'todoapp-583d0.appspot.com',
    androidClientId: '369538743828-tblgedfhjur1s00cm222suu8f76el6gg.apps.googleusercontent.com',
    iosClientId: '369538743828-v904ur87rh5u0e581nnfliqqjmtmhrp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWBEvoPmuUCmqeTOCP66LWEQAKvufujus',
    appId: '1:369538743828:ios:1375c859fa41e346e97101',
    messagingSenderId: '369538743828',
    projectId: 'todoapp-583d0',
    storageBucket: 'todoapp-583d0.appspot.com',
    androidClientId: '369538743828-tblgedfhjur1s00cm222suu8f76el6gg.apps.googleusercontent.com',
    iosClientId: '369538743828-v904ur87rh5u0e581nnfliqqjmtmhrp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
